CREATE TABLE MOBI_STATUS(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL CONSTRAINT PK_MOBI_STATUS_Id PRIMARY KEY (Id))

CREATE TABLE MOBI_BRANCH(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, Address NVARCHAR(Max) NULL
, ZipCode INT NULL, District VARCHAR(200) NULL,Icon VARCHAR(MAX) NULL, Banner VARCHAR(MAX) NULL, StatusId INT NOT NULL,
CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL CONSTRAINT PK_MOBI_BRANCH_Id PRIMARY KEY (Id)
CONSTRAINT FK_BRANCH_MOBI_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id))

CREATE TABLE MOBI_CATAGORY(Id INT IDENTITY(1,1) NOT NULL, Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL,
UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_CATAGORY_Id PRIMARY KEY (Id) 
CONSTRAINT FK_MOBI_CATEGORY_STATUS_Id FOREIGN KEY (StatusId) REFERENCES MOBI_STATUS(Id))
alter table MOBI_CATAGORY add  BranchId INT NULL
alter table MOBI_CATAGORY add CatType int null

CREATE TABLE MOBI_COUNTRY(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_COUNTRY_Id PRIMARY KEY (Id), CONSTRAINT FK_MOBI_COUNTRY_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id))

CREATE TABLE MOBI_STATE(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, COUNTRYId INT NOT NULL ,StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_STATE_Id PRIMARY KEY (Id), CONSTRAINT FK_MOBI_STATE_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id),
CONSTRAINT FK_MOBI_STATE_COUNTRY_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_COUNTRY](Id))

CREATE TABLE MOBI_DISTRICT(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, State INT NOT NULL ,StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_DISTRICT_Id PRIMARY KEY (Id), CONSTRAINT FK_MOBI_DISTRICT_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id),
CONSTRAINT FK_MOBI_DISTRICT_COUNTRY_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATE](Id))


CREATE TABLE MOBI_SUB_CATAGORY(Id INT IDENTITY(1,1) NOT NULL,  Name VARCHAR(50) NOT NULL, Code NVARCHAR(10) NOT NULL, CatagoryId INT NOT NULL,
                               StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL,
CONSTRAINT PK_MOBI_SUB_CATAGORY_Id PRIMARY KEY (Id), 
CONSTRAINT FK_MOBI_SUB_CATAGORY_CATAGORY_Id FOREIGN KEY (CatagoryId) REFERENCES MOBI_CATAGORY(Id),
CONSTRAINT FK_MOBI_SUB_CATAGORY_STATUS_Id FOREIGN KEY (StatusId) REFERENCES MOBI_STATUS(Id))

CREATE TABLE MOBI_PURCHASE(Id INT IDENTITY(1,1) NOT NULL, PurchaseDate DATE NULL, InvoiceNumber VARCHAR(50) NULL, ProductId INT NOT NULL,
ModelId INT NOT NULL, PurchaserName Varchar(200) NULL, PurchaserAddress Varchar(Max) NULL, Quantity INT NOT NULL, Color NVARCHAR(20) NULL, 
ChargerType NVARCHAR(20) NULL, BatteryNumber NVARCHAR(100) NULL, SerialNumber NVARCHAR(100) NULL, IMEINumber NVARCHAR(100) NOT NULL,
GST INT NOT NULL, SGST INT NOT NULL, PurchaseAmount INT NOT NULL, Discount INT NULL, SalesAmount INT NOT NULL, 
StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_PURCHASE_Id PRIMARY KEY (Id), 
CONSTRAINT FK_MOBI_PURCHASE_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id),
CONSTRAINT FK_MOBI_PURCHASE_CATAGORY_Id FOREIGN KEY (ProductId) REFERENCES MOBI_CATAGORY(Id),
CONSTRAINT FK_MOBI_PURCHASE_SUB_CATAGORY_Id FOREIGN KEY (ModelId) REFERENCES MOBI_SUB_CATAGORY(Id))

Alter table MOBI_PURCHASE Add  BranchId int null
Alter table MOBI_PURCHASE Add  Description Varchar(max) null
Alter table MOBI_PURCHASE Add  ProductType bit null
 
CREATE TABLE MOBI_PURCHASE_PRODUCT_Stock(Id INT IDENTITY(1,1) NOT NULL, PurchaseId INT NOT NULL, ProductId INT NOT NULL,
ModelId INT NOT NULL, Quantity INT NOT NULL,  
IMEINumber NVARCHAR(100) NOT NULL,
GST INT NOT NULL, SGST INT NOT NULL, PurchaseAmount INT NOT NULL, Discount INT NULL, SalesAmount INT NOT NULL, 
StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_PURCHASE_PRODUCT_STOCK_Id PRIMARY KEY (Id), 
CONSTRAINT FK_MOBI_PURCHASE_PRODUCT_STOCK_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id),
CONSTRAINT FK_MOBI_PURCHASE_PRODUCT_STOCK_CATAGORY_Id FOREIGN KEY (ProductId) REFERENCES MOBI_CATAGORY(Id),
CONSTRAINT FK_MOBI_PURCHASE_PRODUCT_STOCK_SUB_CATAGORY_Id FOREIGN KEY (ModelId) REFERENCES MOBI_SUB_CATAGORY(Id),
CONSTRAINT FK_MOBI_PURCHASE_PRODUCT_STOCK_PURCHASE_Id FOREIGN KEY (PurchaseId) REFERENCES MOBI_PURCHASE(Id))

Alter table MOBI_PURCHASE_PRODUCT_Stock Add  ProductType bit null
Alter table MOBI_PURCHASE_PRODUCT_Stock Add  BranchId int null
Alter table MOBI_PURCHASE_PRODUCT_Stock Add  IsSold bit null

CREATE TABLE MOBI_SALES(Id INT IDENTITY(1,1) NOT NULL,  BranchId int null,
IMEINumber NVARCHAR(100) NOT NULL,
GST INT NOT NULL, SGST INT NOT NULL, PurchaseAmount INT NOT NULL, Discount INT NULL, SalesAmount INT NOT NULL, 
StatusId INT NOT NULL,CreatedBy INT NULL, CreatedDate DATE NULL, UpdatedBY INT NULL, UpdatedDate DATE NULL 
CONSTRAINT PK_MOBI_SALES_Id PRIMARY KEY (Id), 
CONSTRAINT FK_MOBI_SALES_STATUS_Id FOREIGN KEY (StatusId) REFERENCES [dbo].[MOBI_STATUS](Id))
 